function openMenu(){document.getElementById("mobileMenu")?.classList.add("active")}function closeMenu(){document.getElementById("mobileMenu")?.classList.remove("active")}
const bugImages=["bug1.jpeg","bug2.jpeg","bug3.jpeg","bug4.jpeg","bug5.jpeg","bug6.jpeg","bug7.jpeg","bug8.jpeg","bug9.jpeg","bug10.jpeg","bug11.jpeg","bug12.jpeg","bug13.jpeg","bug14.jpeg","bug15.jpeg","bug16.jpeg","bug17.jpeg","bug18.jpeg"];
const vwImages=["vw1.jpeg","vw2.jpeg","vw3.jpeg","vw4.jpeg","vw5.jpeg","vw6.jpeg"];
const figImages=["fig1.jpeg","fig2.jpeg","fig3.jpeg","fig4.jpeg","fig5.jpeg","fig6.jpeg","fig7.jpeg","fig8.jpeg","fig9.jpeg","fig10.jpeg","fig11.jpeg","fig12.jpeg","fig13.jpeg","fig14.jpeg","fig15.jpeg","fig16.jpeg","fig18.jpeg","fig19.jpeg"];
const mokeImages=["moke1.jpeg","moke2.jpeg","moke3.jpeg","moke4.jpeg","moke5.jpeg","moke6.jpeg","moke7.jpeg","moke8.jpeg","moke9.jpeg","moke10.jpeg","moke11.jpeg","moke13.jpeg","moke14.jpeg"];
const vipImages=["vipshuttle1.jpeg","vipshuttle2.jpeg","vipshuttle3.jpeg","vipshuttle4.jpeg","vipshuttle5.jpeg","vipshuttle6.jpeg","vipshuttle7.jpeg","vipshuttle8.jpeg","vipshuttle9.jpeg","vipshuttle10.jpeg","vipshuttle11.jpeg","vipshuttle12.jpeg","vipshuttle13.jpeg","vipshuttle14.jpeg","vipshuttle15.jpeg","vipshuttle16.jpeg","vipshuttle17.jpeg","vipshuttle18.jpeg"];
const trotterImages=["trottersvan1.jpeg","trottersvan2.jpeg","trottersvan3.jpeg","trottersvan4.jpeg","trottersvan5.jpeg","trottersvan6.jpeg","trottersvan7.jpeg","trottersvan8.jpeg","trottersvan9.jpeg","trottersvan10.jpeg","trottersvan11.jpeg","trottersvan12.jpeg","trottersvan13.jpeg"];
const miniImages=["mini1.jpeg"];const escortImages=["escort1.jpeg"];let currentImages=[];let currentIndex=0;
function openGallery(images,index){currentImages=images;currentIndex=index;showImage();document.getElementById("lightbox")?.classList.add("active")}
function showImage(){const img=document.getElementById("lightboxImg");const counter=document.getElementById("lightboxCounter");if(!img||!counter||!currentImages.length)return;img.src=currentImages[currentIndex];counter.textContent=(currentIndex+1)+" / "+currentImages.length}
function nextImage(){currentIndex=(currentIndex+1)%currentImages.length;showImage()}function prevImage(){currentIndex=(currentIndex-1+currentImages.length)%currentImages.length;showImage()}function closeLightbox(){document.getElementById("lightbox")?.classList.remove("active")}
const lb=document.getElementById("lightbox");if(lb){lb.addEventListener("click",function(e){if(e.target.id==="lightbox")closeLightbox()})}document.addEventListener("keydown",function(e){const lightbox=document.getElementById("lightbox");if(lightbox&&lightbox.classList.contains("active")){if(e.key==="ArrowRight")nextImage();if(e.key==="ArrowLeft")prevImage();if(e.key==="Escape")closeLightbox()}});
